# pull official base image

FROM node:18.14.1 as build

# install and cache app dependencies

COPY package.json ./

COPY yarn.lock ./

RUN yarn install

COPY . .

EXPOSE 3000

# start app

CMD ["yarn", "start"]